version: '3.9'

services:
  database:
    container_name: ctr-db-calendar
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    container_name: ctr-adminer
    environment:
      - DATABASE_URL=postgres://root:root@database:5432/db_calendar
    ports:
      - 5000:8080
